# Default initial positions for name's ros2_control fake system
  
initial_positions:
  shoulder_pan_joint: 0.0
  elbow_joint: 0.0
  robotiq_85_left_knuckle_joint: 0.0
  shoulder_lift_joint: 0.0

  wrist_1_joint: 0.0
  wrist_2_joint: 0.0
  wrist_3_joint: 0.0